# Generated by Django 5.2 on 2025-05-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('contenido', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('autor', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='articulosimg/')),
                ('valorunidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(upload_to='Categoriasimg/')),
            ],
        ),
    ]
