# Generated by Django 5.2 on 2025-06-25 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_direccion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='direccion',
            old_name='direccion',
            new_name='direccion_texto',
        ),
    ]
