# Generated by Django 5.2 on 2025-06-25 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
